name: Convert README to JSON

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pandoc python3-pip
          pip install markdown2

      - name: Convert README to JSON
        run: |
          python3 -c """
import json
import markdown2
import re

with open('README.md', 'r', encoding='utf-8') as f:
    md_content = f.read()

sections = re.split(r'## ', md_content)
api_data = {}

for section in sections[1:]:
    lines = section.split('\n')
    category = lines[0].strip()
    table_start = next((i for i, line in enumerate(lines) if '|' in line), None)
    
    if table_start is not None:
        headers = [h.strip() for h in lines[table_start].split('|')[1:-1]]
        api_data[category] = []
        for line in lines[table_start+2:]:
            columns = [col.strip() for col in line.split('|')[1:-1]]
            if len(columns) == len(headers):
                api_data[category].append(dict(zip(headers, columns)))

with open('README.json', 'w', encoding='utf-8') as f:
    json.dump(api_data, f, indent=2, ensure_ascii=False)
          """

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.json
          git commit -m 'Auto-generate README.json from README.md' || echo "No changes to commit"
          git push
